server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/summer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml